name: Motif Scanner Rust

on:
  push:
    branches: ['master']
    paths:
      - 'motif-scanner/src/**'
      - 'motif-scanner/tests/**'
  pull_request:
    branches: ['master']
    paths:
      - 'motif-scanner/src/**'
      - 'motif-scanner/tests/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build -p motif-scanner --verbose
      - name: Run tests
        run: cargo test -p motif-scanner --verbose
