name: Rust

on:
  push:
    branches: ['master']
    paths:
      - 'tf-binding-rs/**'
      - 'motif-scanner/**'
  pull_request:
    branches: ['master']
    paths:
      - 'tf-binding-rs/**'
      - 'motif-scanner/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --workspace --verbose
      - name: Run tests
        run: cargo test --workspace --verbose
